INDIGO_WELCOME_MESSAGE: "四川大学锦城学院"
INDIGO_PRIMARY_COLOR: "#3b85ff" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "注意"
      url: "/tos"
    - title: "四川大学锦城学院"
      url: "https://www.scujcc.edu.cn"
